### ISSUE TITLE
Demo Link Dead

### ISSUE THREAD

**Issue by haraphat01** [fgrehm/letter_opener_web_demo#1]
Hi,
I was just checking the letter_opener_web gem, I noticed the link to the demo on heroku is no more live, I'm calling your attention to it in case you are not aware.

**Comment by fgrehm** [comment]
Hey @haraphat01! Sorry for the long silence here, and yeah, there's no more free tier on Heroku so the demo is no longer available.

I just added a note to the readme and will archive this repository next.
